public enum PROTOCOL
{
    ID_HANDLE_FORWORD_STOP = 0,
    ID_HANDLE_FORWORD_OPEN = 1,
    ID_HANDLE_FORWORD_CLOSE = 2,
    ID_HANDLE_FORWORD_STATE = 3,

    ID_HANDLE_TILTING_STOP = 4,
    ID_HANDLE_TILTING_OPEN = 5,
    ID_HANDLE_TILTING_CLOSE = 6,
    ID_HANDLE_TILTING_STATE = 7,

    ID_SIDE_MIRROW_LEFT_STOP = 8,
    ID_SIDE_MIRROW_LEFT_OPEN = 9,
    ID_SIDE_MIRROW_LEFT_CLOSE = 10,
    ID_SIDE_MIRROW_LEFT_STATE = 11,

    ID_SIDE_MIRROW_RIGHT_STOP = 12,
    ID_SIDE_MIRROW_RIGHT_OPEN = 13,
    ID_SIDE_MIRROW_RIGHT_CLOSE = 14,
    ID_SIDE_MIRROW_RIGHT_STATE = 15,

    ID_FRONT_DOOR_KEY_LEFT_STOP = 16,
    ID_FRONT_DOOR_KEY_LEFT_LOCK = 17,
    ID_FRONT_DOOR_KEY_LEFT_UNLOCK = 18,
    ID_FRONT_DOOR_KEY_LEFT_STATE = 19,

    ID_FRONT_DOOR_KEY_RIGHT_STOP = 20,
    ID_FRONT_DOOR_KEY_RIGHT_LOCK = 21,
    ID_FRONT_DOOR_KEY_RIGHT_UNLOCK = 22,
    ID_FRONT_DOOR_KEY_RIGHT_STATE = 23,

    ID_CONSOLE_TOP_STOP = 24,
    ID_CONSOLE_TOP_OPEN = 25,
    ID_CONSOLE_TOP_CLOSE = 26,
    ID_CONSOLE_TOP_STATE = 27,

    ID_HANDLE_CIRCLE_STOP = 28,
    ID_HANDLE_CIRCLE_OPEN = 29,
    ID_HANDLE_CIRCLE_CLOSE = 30,
    ID_HANDLE_CIRCLE_STATE = 31,

    ID_TAIL_GATE_DOOR_LEFT_STOP = 32,
    ID_TAIL_GATE_DOOR_LEFT_OPEN = 33,
    ID_TAIL_GATE_DOOR_LEFT_CLOSE = 34,
    ID_TAIL_GATE_DOOR_LEFT_STATE = 35,

    ID_TAIL_GATE_DOOR_RIGHT_STOP = 36,
    ID_TAIL_GATE_DOOR_RIGHT_OPEN = 37,
    ID_TAIL_GATE_DOOR_RIGHT_CLOSE = 38,
    ID_TAIL_GATE_DOOR_RIGHT_STATE = 39,

    ID_EMERGENCE_STOP = 40,

    ID_CONSOLE_BOTTOM_STOP = 41,
    ID_CONSOLE_BOTTOM_OPEN = 42,
    ID_CONSOLE_BOTTOM_CLOSE = 43,
    ID_CONSOLE_BOTTOM_STATE = 44,
}

public enum RAONTEC_PC_Controll
{
    MSG_POWER_OFF       =   3001,
    MSG_POWER_RESET     =   3002
}
public enum Hansol_PC_Controll
{
    MSG_POWER_OFF       =   3001,
    MSG_POWER_RESET     =   3002
}

public enum Mobile_PROTOCOL
{
    ID_DRIVE_MODE = 2000,
    ID_REST_MODE = 2001,
    ID_SIDE_MIRROW_OPEN = 2002,
    ID_SIDE_MIRROW_CLOSE = 2003,
    ID_FRONT_DOOR_LOCK_OPEN = 2004,
    ID_FRONT_DOOR_LOCK_CLOSE = 2005,
    ID_CONSOLE_TOP_UP = 2006,
    ID_CONSOLE_TOP_DOWN = 2007,
    ID_CONSOLE_BOTTOM_UP = 2008,
    ID_CONSOLE_BOTTOM_DOWN = 2009,
    ID_HANDLE_STEERING_WHEEL_OPEN = 2010,
    ID_HANDLE_STEERING_WHEEL_CLOSE = 2011,
    ID_TAIL_GATE_DOOR_LEFT_OPEN = 2012,
    ID_TAIL_GATE_DOOR_LEFT_CLOSE = 2013,
    ID_TAIL_GATE_DOOR_RIGHT_OPEN = 2014,
    ID_TAIL_GATE_DOOR_RIGHT_CLOSE = 2015,
    ID_SOUND_VOLUME = 2300,
    ID_POWER_OFF = 2301,
    ID_POWER_ON = 2302,
    ID_LIGHT_CHANGE_01 = 2303,
    ID_LIGHT_CHANGE_02 = 2304,
    ID_LIGHT_CHANGE_03 = 2305,
    ID_LIGHT_CHANGE_04 = 2306,



    ID_EMERGENCT_LIGHT_ON = 3000,               //0x55
    ID_EMERGENCT_LIGHT_OFF = 3001,
    ID_BREAK_LIGHT_ON = 3002,                   //0x56
    ID_BREAK_LIGHT_OFF = 3003,


    ID_TURN_LEFT_ON = 4000,                     //0x57
    ID_TURN_LEFT_OFF = 4001,                    
    ID_TURN_RIGHT_ON = 4002,                    //0x58
    ID_TURN_RIGHT_OFF = 4003,
    ID_DRL_ON = 4004,                           //0x59
    ID_DRL_OFF = 4005,
    ID_LIGHT_HIGH_ON = 4006,                    //0x60
    ID_LIGHT_HIGH_OFF = 4007,
    ID_LIGHT_LOW_ON = 4008,                     //0x61
    ID_LIGHT_LOW_OFF = 4009,


    ID_RESET_IDLE_OFF = 4040,                   //아이들 OFF
    ID_RESET_IDLE_STATE = 4010,                 //0x62  ON


    ID_ALL_LIGHT_ON = 4011,                     //0x63 실내등 ON
    ID_ALL_LIGHT_OFF = 4012,                    //실내등 OFF

    ID_CLUTCH_ON = 4013,
    ID_CLUTCH_OFF = 4014,
    ID_ELECTROMAGNET_ON = 4015,
    ID_ELECTROMAGNET_OFF = 4016,
    ID_DRIVE_MOTOR_ON = 4017,
    ID_DRIVE_MOTOR_OF = 4018,
    ID_REAR_DOOR_TOUCH_LOCK_ON = 4019,
    ID_REAR_DOOR_TOUCH_LOCK_OFF = 4020,


    ID_DISPLAY_MOVIE_01 = 5000,
    ID_DISPLAY_MOVIE_02 = 5001,
    ID_DISPLAY_MOVIE_03 = 5002,
    ID_DISPLAY_MOVIE_STOP = 5003,
    ID_DISPLAY_ALL_ON   =   5004,

    ID_EMERGENCE        = 2100,

    ID_PC_OFF           =   6000,


    MSG_RAONTECCONNECT_ON   =   8899,
    MSG_RAONTECCONNECT_OFF  =   9988

}
public enum MOTION_PROTOCOL
{
    ID_Reset_RecivePacket = 0x10 
}
public enum DISPLAYPORT
{
    ID_FRONT    = 0,
    ID_CPAD     = 1,
    ID_DHS_L    = 2,
    ID_DHS_R    = 3,
    ID_DHF_L    = 4,
    ID_DHF_R    = 5,
    ID_TAIL_L   = 6,
    ID_TAIL_R   = 7
}
public enum HANSOL_SYNC_DISPLAY
{
    ID_LEFT_DISPLAY_IDLE    =   6000,
    ID_LEFT_DISPLAY_OPEN    =   6001,
    ID_LEFT_DISPLAY_CLOSE   =   6002,

    ID_RIGHT_DISPLAY_IDLE   =   6003,
    ID_RIGHT_DISPLAY_OPEN   =   6004,
    ID_RIGHT_DISPLAY_CLOSE  =   6005,

    ID_BACK_DISPLAY_IDLE    =   6006,
    ID_BACK_DISPLAY_OPEN    =   6007,
    ID_BACK_DISPLAY_CLOSE   =   6008,

    ID_DISPLAY_ON           =   8000, // on
    ID_DISPLAY_OFF          =   8001    // off
}